package com.example.ecgclassifier

class Constants {
    val diagnosisTaskLabels = arrayListOf(
            "1 AV block",
            "2 AV block",
            "3 AV block",
            "Anterolateral Myocardial Infarction",
            "AMI",
            "Anterolateral Myocardial Infarction",
            "Anteroseptal Myocardial Infarction",
            "Complete Left Bundle Branch Block",
            "Complete Right Bundle Branch Block",
            "Digitalis-effect",
            "Electrolytic Disturbance or Drug (former EDIS)",
            "Incomplete Left Bundle Branch Block",
            "Inferolateral Myocardial Infarction",
            "Inferior Myocardial Infarction",
            "Subendocardial Injury in Anterolateral Leads",
            "Subendocardial Injury in Anteroseptal Leads",
            "Subendocardial Injury in Inferolateral Leads",
            "Subendocardial Injury in Inferior Leads",
            "Subendocardial Injury in Lateral Leads",
            "Inferoposterolateral Myocardial Infarction",
            "Inferoposterior Myocardial Infarction",
            "Incomplete Right Bundle Branch Block",
            "Ischemic in Anterolateral Leads",
            "Ischemic in Anterior Leads",
            "Ischemic in Anteroseptal Leads",
            "Ischemic in Inferolateral Leads",
            "Ischemic in Inferior Leads",
            "Ischemic in Lateral Leads",
            "Non-specific Ischemic",
            "Non-specific Intraventricular conduction disturbance (block)",
            "Left Anterior Fascicular Block",
            "Left Atrial Overload/Enlargement",
            "Lateral Myocardial Infarction",
            "Long QT-Interval",
            "Left Posterior Fascicular Block",
            "Left Ventricular Hypertrophy",
            "Non-diagnostic T Abnormalities",
            "NORMAL",
            "Non-specific ST Changes",
            "Posterior Myocardial Infarction",
            "Right Atrial Overload/Enlargement",
            "Right Ventricular Hypertrophy",
            "Septal hypertrophy",
            "Wolff-Parkinson-White syndrome"
    )

    val subDiagnosisTaskLabels = arrayListOf("AMI", "CLBBB", "CRBBB", "ILBBB", "IMI", "IRBBB", "ISCA", "ISCI", "ISC_", "IVCD", "LAFB/LPFB", "LAO/LAE", "LMI", "LVH", "NORM", "NST_", "PMI", "RAO/RAE", "RVH", "SEHYP", "STTC", "WPW", "_AVB")
    val superDiagnosisTaskLabels = arrayListOf("CD", "HYP", "MI", "NORM", "STTC")

//    DIAGNOSIS ACRONYM
//    val labelsList = arrayListOf(
//            "1AVB",
//            "2AVB",
//            "3AVB",
//            "ALMI",
//            "AMI",
//            "ANEUR",
//            "ASMI",
//            "CLBBB",
//            "CRBBB",
//            "DIG",
//            "EL",
//            "ILBBB",
//            "ILMI",
//            "IMI",
//            "INJAL",
//            "INJAS",
//            "INJIL",
//            "INJIN",
//            "INJLA",
//            "IPLMI",
//            "IPMI",
//            "IRBBB",
//            "ISCAL",
//            "ISCAN",
//            "ISCAS",
//            "ISCIL",
//            "ISCIN",
//            "ISCLA",
//            "ISC_",
//            "IVCD",
//            "LAFB",
//            "LAO/LAE",
//            "LMI",
//            "LNGQT",
//            "LPFB",
//            "LVH",
//            "NDT",
//            "NORM",
//            "NST_",
//            "PMI",
//            "RAO/RAE",
//            "RVH",
//            "SEHYP",
//            "WPW"
//    )
}